# This is a basic workflow to help you get started with Actions

name: Andriod CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.


build-debug-apk:
      strategy:
        fail-fast: false
        matrix:
          agp: [ "" ]
          kotlin: [ "" ]
          experimental: [ false ]
          name: [ "stable" ]
          include:
            - agp: 4.2.+
              experimental: true
              name: AGP-4.2.+
            - kotlin: 1.4.20+
              experimental: true
              name: kotlin-EAP-1.4.20+

      continue-on-error: ${{ matrix.experimental }}
      name: Build Debug APK - ${{ matrix.name }} - Experimental ${{ matrix.experimental }}
      env:
        VERSION_AGP: ${{ matrix.agp }}
        VERSION_KOTLIN: ${{ matrix.kotlin }}